services:
  api:
    container_name: libreNano
    ports:
      - '${PORT:-3080}:${PORT:-3080}'
    image: librechat:local
    build:
      context: .
      dockerfile: Dockerfile.optimized
      target: runtime
    restart: always
    user: '${UID:-1000}:${GID:-1000}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - HOST=0.0.0.0
      - PORT=${PORT:-3080}
      - MONGO_URI=${MONGO_URI}
      - SEARCH=false
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/logs
